#!/bin/bash

#monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#window information
bspc config border_width 0 
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

#rules
bspc rule -a mumble state=floating follow=on focus=on

#autostart
setxkbmap fr
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
feh --bg-fill ~/Pictures/wall/neon-genesis-evangelion-wallpaper.jpg
~/.config/polybar/launch.sh
